MODIFIERS_TOKEN_ALIASES: dict[str, str] = {
    # Typos / variants -> canonical token (All Words Capitalised)
    "AD": "AD",
    "AP": "AP",
    "% AD": "% AD",
    "% AP": "% AP",
    "% armor": "% Armor",
    "% bonus AD": "% Bonus AD",
    "% bonus armor": "% Bonus Armor",
    "% bonus health": "% Bonus Health",
    "% bonus magic resistance": "% Bonus Magic Resistance",
    "% bonus mana": "% Bonus Mana",
    "% bonus movement speed": "% Bonus Movement Speed",
    "% life steal": "% Life Steal",
    "% maximum health": "% Maximum Health",
    "% maximum mana": "% Maximum Mana",
    "% missing health": "% Missing Health",
    "% missing mana": "% Missing Mana",
    "% total armor": "% Total Armor",
    "% total magic resistance": "% Total Magic Resistance",
    "% per 1% missing health": "% Per 1% Missing Health",
    "% per 1% of health lost in the past 4 seconds": (
        "% Per 1% of Health Lost in the Past 4 Seconds"
    ),
    "% per 100 AD": "% Per 100 AD",
    "% per 100 AP": "% Per 100 AP",
    "% per 100 bonus AD": "% Per 100 Bonus AD",
    "% per 100 bonus armor": "% Per 100 Bonus Armor",
    "% per 100 bonus health": "% Per 100 Bonus Health",
    "% per 100 bonus magic resistance": "% Per 100 Bonus Magic Resistance",
    "% per 100 of Sona's AP": "% Per 100 of Sona's AP",
    "% per 100 Pantheon's bonus health": "% Per 100 Pantheon's Bonus Health",
    "% per 100% bonus attack speed": "% Per 100% Bonus Attack Speed",
    "% per 4% critical strike chance": "% Per 4% Critical Strike Chance",
    "% per Feast stack": "% Per Feast Stack",
    "% per Mark": "% Per Mark",
    "% per Mist collected": "% Per Mist Collected",
    "% per Overwhelm stack on the target": "% Per Overwhelm Stack on the Target",
    "% per Soul collected": "% Per Soul Collected",
    "% of Braum's maximum health": "% of Braum's Maximum Health",
    "% of Ivern's AP": "% of Ivern's AP",
    "% of Siphoning Strike stacks": "% of Siphoning Strike Stacks",
    "% of Sona's AP": "% of Sona's AP",
    "% of Taric's armor": "% of Taric's Armor",
    "% of Zac's maximum health": "% of Zac's Maximum Health",
    "% of damage dealt": "% of Damage Dealt",
    "% of damage stored": "% of Damage Stored",
    "% of her maximum health": "% of Her Maximum Health",
    "% of his bonus health": "% of His Bonus Health",
    "% of his maximum health": "% of His Maximum Health",
    "% of his missing health": "% of His Missing Health",
    "% of missing health": "% of Missing Health",
    "% of missing mana": "% of Missing Mana",
    "% of primary target's bonus health": "% of Primary Target's Bonus Health",
    "% of target's armor": "% of Target's Armor",
    "% of target's current health": "% of Target's Current Health",
    "% of target's maximum health": "% of Target's Maximum Health",
    "% of target's missing health": "% of Target's Missing Health",
    "% of turret's maximum health": "% of Turret's Maximum Health",
    "% of maximum health": "% of Maximum Health",
    "AP per 100 bonus health": "AP per 100 Bonus Health",
    "Braum's maximum health": "Braum's Maximum Health",
    "Ivern's AP": "Ivern's AP",
    "Moonlight": "Moonlight",
    "Siphoning Strike stacks": "Siphoning Strike Stacks",
    "Sona's AP": "Sona's AP",
    "Stacks": "Stacks",
    "Style": "Style",
    "Taric's armor": "Taric's Armor",
    "Zac's maximum health": "Zac's Maximum Health",
    "armor": "Armor",
    "bonus AD": "Bonus AD",
    "bonus armor": "Bonus Armor",
    "bonus health": "Bonus Health",
    "bonus magic resistance": "Bonus Magic Resistance",
    "bonus mana": "Bonus Mana",
    "bonus movement speed": "Bonus Movement Speed",
    "chunks of ice": "Chunks of Ice",
    "critical strike chance": "Critical Strike Chance",
    "damage dealt": "Damage Dealt",
    "damage stored": "Damage Stored",
    "expended Grit": "Expended Grit",
    "her maximum health": "Her Maximum Health",
    "his bonus health": "His Bonus Health",
    "his maximum health": "His Maximum Health",
    "his missing health": "His Missing Health",
    "level": "Level",
    "life steal": "Life Steal",
    "mana": "Mana",
    "maximum": "Maximum",
    "maximum health": "Maximum Health",
    "maximum mana": "Maximum Mana",
    "missing health": "Missing Health",
    "missing mana": "Missing Mana",
    "original damage": "Original Damage",
    "per 1% missing health": "Per 1% Missing Health",
    "per 1% of health lost in the past 4 seconds": "Per 1% of Health Lost in the Past 4 Seconds",
    "per 100 AD": "Per 100 AD",
    "per 100 AP": "Per 100 AP",
    "per 100 Pantheon's bonus health": "Per 100 Pantheon's Bonus Health",
    "per 100 bonus AD": "Per 100 Bonus AD",
    "per 100 bonus armor": "Per 100 Bonus Armor",
    "per 100 bonus health": "Per 100 Bonus Health",
    "per 100 bonus magic resistance": "Per 100 Bonus Magic Resistance",
    "per 100 of Sona's AP": "Per 100 of Sona's AP",
    "per 100% bonus attack speed": "Per 100% Bonus Attack Speed",
    "per 4% critical strike chance": "Per 4% Critical Strike Chance",
    "per Feast stack": "Per Feast Stack",
    "per Mark": "Per Mark",
    "per Mist collected": "Per Mist Collected",
    "per Overwhelm stack on the target": "Per Overwhelm Stack on the Target",
    "per Soul collected": "Per Soul Collected",
    "primary target's bonus health": "Primary Target's Bonus Health",
    "seconds": "Seconds",
    "soldiers": "Soldiers",
    "target's armor": "Target's Armor",
    "target's current health": "Target's Current Health",
    "target's maximum health": "Target's Maximum Health",
    "target's missing health": "Target's Missing Health",
    "total armor": "Total Armor",
    "total magic resistance": "Total Magic Resistance",
    "turret's maximum health": "Turret's Maximum Health",
    "units": "Units",
}
